### ISSUE TITLE
app name overridden by string res app_name

### ISSUE THREAD

**Issue by rakshitsoni02** [rudderlabs/rudder-integration-firebase-android#11]
Hi Team,

is that possible to remove the app name from the string res file as it's overriding our prod app name in the release builds?
related to https://github.com/rudderlabs/rudder-sdk-android/pull/134

`<string name="app_name">RudderAndroidSdkCore</string> `

**Comment by desusai7** [comment]
Hey @rakshitsoni02 , 
Thank you for bringing this up, we will work on this.

**Comment by desusai7** [comment]
Hey @rakshitsoni02, 
We had released version `2.0.3` with this particular string resource removed. Can you please upgrade to that and let us know if the issue is fixed. 

We are also removing this from all the android device modes which contain them.

**Comment by rakshitsoni02** [comment]
awesome 🎉
works fine now. 
thanks, @desusai7
